name: Update Docker Hub description

on:
  push:
    paths:
      - Docker/README.md
    branches:
      - edge
  workflow_dispatch:

jobs:
  dockerhub-description:
    if: github.repository_owner == 'FreshRSS'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update repo description
      uses: peter-evans/dockerhub-description@0505d8b04853a30189aee66f5bb7fd1511bbac71
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: freshrss/freshrss
        readme-filepath: Docker/README.md
